version: "3"

services:
  web:
    image: "nginx"
    restart: "unless-stopped"
    volumes:
      - "./:/usr/share/nginx/html"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:ignaciusbros.codeisc.com"
      - "traefik.port=80"
    networks:
      - traefik

networks:
  traefik:
    external: "true"
